### ISSUE TITLE
Compatibility with 4.X

### ISSUE THREAD

**Issue by ceedriic** [HugoHasenbein/redmine_attachment_categories#1]
Hello,

Could you tell me if that plugin is supposed to be compatible with 4.0 and the upcoming 4.1?

Thanks,

**Comment by mukkoo** [comment]
@ceedriic I've tried to resolve with this PR https://github.com/HugoHasenbein/redmine_attachment_categories/pull/2

**Comment by CNPF** [comment]
I Stephan

I confirme, the version works https://github.com/mukkoo/redmine_attachment_categories/tree/4x_compatibility 

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.11.0
  Filesystem

**Comment by CNPF** [comment]
Hi Stephan
I confirme,  this branch is correct git clone -b 4x_compatibility https://github.com/mukkoo/redmine_attachment_categories.git

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.4.1

**Comment by HugoHasenbein** [comment]
2.0.0 now conmpatible with 4.1

**Comment by HugoHasenbein** [comment]
now compatible with RM4+
